sudo: required
services:
  - docker

before_install:
  - docker build -t dmayer2/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true dmayer2/react-test npm test

after_success:
  - docker build -t dmayer2/multi-client ./client
  - docker build -t dmayer2/multi-nginx ./nginx
  - docker build -t dmayer2/multi-server ./server
  - docker build -t dmayer2/multi-worker ./worker
  # log in to the docker CLI --> variables on Travis
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push dmayer2/multi-client
  - docker push dmayer2/multi-nginx
  - docker push dmayer2/multi-server
  - docker push dmayer2/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-346862844235
  bucket_path: docker-multi
  on: 
    branch: master
access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY

language: generic 